server:
  servlet:
    context-path: /investment-assist

spring:
  application:
    name: investment-assist

  threads:
    virtual:
      enabled: true


api:
  bcb:
    url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.%d/dados/ultimos/%d?formato=json"
    selic-code: 1178
    cdi-code: 4389
    ipca-code: 433